name: Build

on: [ push, pull_request ]

jobs:
  dist:
    name: Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install SDL
      run: |
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev
    - name: Configure
      run: |
        cd sdlmine && ./autogen.sh && ./configure && cd ..
        cd sdlreversi && ./autogen.sh && ./configure && cd ..
        cd spidersol && ./autogen.sh && ./configure && cd ..
    - name: Make source packages
      run: |
        cd sdlmine && make dist && cd ..
        cd sdlreversi && make dist && cd ..
        cd spidersol && make dist && cd ..
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          sdlmine/sdlmine-1.0.tar.gz
          sdlreversi/sdlreversi-1.0.tar.gz
          spidersol/spidersol-1.0.tar.gz
